#!/bin/sh

set -e

CAPJS_NAME="libcapjs.so"
CAPJS_PATH="/usr/lib64/capjs/$CAPJS_NAME"

for DB_TYPE in "mariadb" "mysql"
do
    for PLUGIN_DIR in "plugin" "plugins"
    do
        DB_DIRECTORY="/usr/lib64/$DB_TYPE/$PLUGIN_DIR"
        if [ -d $DB_DIRECTORY ]; then
            ln -vsf $CAPJS_PATH "$DB_DIRECTORY/$CAPJS_NAME"
        fi
    done
done

exit 0
